### ISSUE TITLE
TypeError when playing for some time

### ISSUE THREAD

**Issue by chocoelho** [SpaceWars/spacewars#3]
There's an error when playing for some time. It happened while shooting random objects, be it space ship or rock.

```
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 116, in main
    director.run(scene)
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/cocos/director.py", line 406, in run
    event_loop.run()
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/app/base.py", line 136, in run
    self._run_estimated()
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/app/base.py", line 165, in _run_estimated
    timeout = self.idle()
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/app/base.py", line 280, in idle
    window.dispatch_event('on_draw')
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1154, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/event.py", line 358, in dispatch_event
    self._raise_dispatch_exception(event_type, args, handler)
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/event.py", line 355, in dispatch_event
    if handler(*args):
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/cocos/director.py", line 460, in on_draw
    self.scene.visit()
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/cocos/cocosnode.py", line 734, in visit
    self.draw()
  File "/home/chocoelho/projects/spacewars/src/game/scenes.py", line 237, in draw
    "Aerolite", self.waves / 2)
  File "/home/chocoelho/projects/spacewars/src/engine/enemy.py", line 76, in create_enemy
    enemy_type, qnt - len(cls.enemy_list[enemy_type]))
  File "/home/chocoelho/projects/spacewars/src/engine/enemy.py", line 50, in populate_enemy
    for x in range(0, qnt):
TypeError: 'float' object cannot be interpreted as an integer
```

**Comment by chocoelho** [comment]
Turns out, this happened due to a float division when generating `Aerolite` enemies. Fixed in f15f849.
