### ISSUE TITLE
Error when trying to play victory file

### ISSUE THREAD

**Issue by chocoelho** [SpaceWars/spacewars#4]
```
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    main()
  File "main.py", line 116, in main
    director.run(scene)
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/cocos/director.py", line 406, in run
    event_loop.run()
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/app/base.py", line 136, in run
    self._run_estimated()
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/app/base.py", line 165, in _run_estimated
    timeout = self.idle()
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/app/base.py", line 280, in idle
    window.dispatch_event('on_draw')
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1154, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/event.py", line 355, in dispatch_event
    if handler(*args):
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/cocos/director.py", line 460, in on_draw
    self.scene.visit()
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/cocos/cocosnode.py", line 734, in visit
    self.draw()
  File "/home/chocoelho/projects/spacewars/src/game/scenes.py", line 226, in draw
    pyglet.resource.media(victory, streaming=False).play()
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/resource.py", line 629, in media
    return media.load(path, streaming=streaming)
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/media/__init__.py", line 1429, in load
    source = get_source_loader().load(filename, file)
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/media/__init__.py", line 1410, in load
    return riff.WaveSource(filename, file)
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/media/riff.py", line 193, in __init__
    format = wave_form.get_format_chunk()
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/media/riff.py", line 173, in get_format_chunk
    for chunk in self.get_chunks():
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/media/riff.py", line 109, in get_chunks
    chunk = cls(self.file, name, length, offset)
  File "/home/chocoelho/.virtualenvs/spacewars/lib/python3.6/site-packages/pyglet/media/riff.py", line 154, in __init__
    raise RIFFFormatException('Size of format chunk is incorrect.')
pyglet.media.riff.RIFFFormatException: Size of format chunk is incorrect.
```

**Comment by chocoelho** [comment]
Binary WAV file was corrupt, fixed in 499adef.
